name: windows_build_test
on: [pull_request]
env:
  SOLUTION_FILE_PATH: RhythmActionGame.sln

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        configuration:
          - Debug
          - Release
    
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
    
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
    
      - shell: powershell
        run: |
          msbuild $env:SOLUTION_FILE_PATH /t:Clean /p:Platform=x64,Configuration=${{ matrix.configuration }}
          msbuild $env:SOLUTION_FILE_PATH /t:Build /m /p:Platform=x64,Configuration=${{ matrix.configuration }}
